---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: spedge
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      initContainers:
        # Generate ACL file from secrets - keeps passwords out of ConfigMaps
        - name: acl-generator
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              cat > /acl/users.acl << EOF
              user ${ADMIN_USER} on allkeys +@all ~* >${ADMIN_PASS}
              user ${NODERED_USER} on allkeys +@read +@write +@stream \
                +@pubsub +@connection +info -@admin -@dangerous ~* >${NODERED_PASS}
              user ${MONITOR_USER} on allkeys +@read +ping +info +client \
                +cluster +pubsub -@admin -@dangerous -@write ~* >${MONITOR_PASS}
              user default off -@all
              EOF
              chmod 400 /acl/users.acl
          env:
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: admin-username
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: admin-password
            - name: NODERED_USER
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: nodered-username
            - name: NODERED_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: nodered-password
            - name: MONITOR_USER
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: monitor-username
            - name: MONITOR_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: monitor-password
          volumeMounts:
            - name: redis-acl
              mountPath: /acl
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: redis
          image: redis:8.2.2-alpine
          args:
            - redis-server
            - --aclfile
            - /etc/redis/users.acl
            - --maxmemory
            - 768mb
            - --maxmemory-policy
            - allkeys-lru
            - --save
            - "900"
            - "1"
            - --save
            - "300"
            - "10"
            - --save
            - "60"
            - "10000"
            - --appendonly
            - "yes"
            - --appendfsync
            - everysec
            - --protected-mode
            - "no"
            - --bind
            - 0.0.0.0
            - --tcp-backlog
            - "511"
            - --timeout
            - "300"
            - --tcp-keepalive
            - "60"
          env:
            # For health probes - credentials from secrets
            - name: REDIS_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: admin-username
            - name: REDIS_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: admin-password
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-acl
              mountPath: /etc/redis
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli --user $REDIS_ADMIN_USER -a $REDIS_ADMIN_PASS --no-auth-warning ping
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli --user $REDIS_ADMIN_USER -a $REDIS_ADMIN_PASS --no-auth-warning ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      # Run pod as redis user (uid 999 in alpine image)
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-acl
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: spedge
  labels:
    app: redis
spec:
  # ClusterIP - only accessible within the cluster
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
